[package]
name = "libcosmic"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[dependencies]
cascade = "1.0.0"
gtk4 = { version = "0.4.4", features = ["v4_4"] }
gdk4 = "0.4.4"
gdk4-wayland = { version = "0.4.2", features = [ "wayland_crate" ], optional = true }
gdk4-x11 = { version = "0.4.2", features = [ "xlib" ] }
gio = "0.15.2"
gobject-sys = "0.15.1"
wayland-client = { version = "0.29.4", optional = true }
wayland-protocols = { version = "0.29.4", features = [ "client", "unstable_protocols" ], optional = true }
x11 = { version = "2.19.1", features = ["xlib"] }
once_cell = "1.9.0"

[features]
layer-shell = ["gdk4-wayland", "wayland-client", "wayland-protocols"]
